In [42]:
from selenium import webdriver
        import pandas as pd
        import numpy as np
pathToChrome = 'C:\chromedriver.exe'
url ='https://osu.ppy.sh/rankings/osu/performance?page='
browser = webdriver.Chrome(pathToChrome)

In [47]:
# Initializing dictionaries of lists to parse info about osu players
players = {}
players['nick'] = []
players['country'] = []
players['accuracy'] = []
players['ss'] = []
players['s'] = []
players['a'] = []

In [48]:

# iterate through site of osu
till = 1000
for i in range(1, int(till/50)+1):
    browser.get(url + str(i) + '#scores')
    try:
        # since site doesn't allow to take info by class or attributes we look for the whole column
        playerInfo = browser.find_elements_by_class_name('ranking-page-table__column')
    except:
        print('BRUH')
    finally: 
        for i in range(0,len(playerInfo),8):
            players['nick'].append(playerInfo[i+1].text)
            players['country'].append(playerInfo[i+2].text)
            players['accuracy'].append(playerInfo[i+3].text)
            players['ss'].append(playerInfo[i+4].text)
            players['s'].append(playerInfo[i+5].text)
            players['a'].append(playerInfo[i+6].text)
        playersFrame = pd.DataFrame(players)

The data of osu players

In [49]:
playersFrame

               nick  country accuracy      ss    s      a
0             mrekk  98,44 %  120 018  21 429   46    965
1            aetrna  97,42 %  153 358  19 105  141    638
2          WhiteCat  98,59 %   32 435  18 817   38    360
3              RyuK  98,91 %  229 394  18 475  196  2 946
4        NyanPotato  97,19 %  122 639  18 045   15    423
..              ...      ...      ...     ...  ...    ...
995        kanocchi  98,66 %   41 984  10 539   39    699
996          Delete  98,91 %  135 898  10 539   14    627
997          Hifkil  98,83 %   36 258  10 538   14    459
998  rbhby njlj1707  98,85 %   50 239  10 537   24    295
999          Ryniix  98,64 %   44 725  10 536   29    426

[1000 rows x 6 columns]